<a href="https://colab.research.google.com/github/Adansote/curso_freecodecamp_NUMPY/blob/main/Basicos_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**basicos de numpy**

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [4]:
#dimecion del array
a.ndim

1

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.nbytes

24

In [9]:
a.size

3

**Acceder/Modificar elementos, filas, columnas, etc. específicos,**

In [10]:
aa = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print( aa)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#Obtener un elemento específico [r, c]
aa[1,5]

np.int64(13)

In [12]:
#Obtener una fila específica
aa[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#Obtener una columna específica
aa[:, 2]

array([ 3, 10])

In [ ]:
#Un poco más sofisticado [índice de inicio:índice de fin:tamaño del paso]

In [14]:
aa[0,1:-1:2]

array([2, 4, 6])

In [15]:
aa[1,5] =20

In [16]:
aa[:, 2]=[1,2]

In [18]:
print(aa)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
bb =np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(bb)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [19]:
#Obtener elemento específico (trabajar de afuera hacia adentro)
bb[0,1,1]

np.int64(4)

In [20]:
#remplasando
bb[:,1,:] =[[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
bb

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

**Inicialización de diferentes tipos de matrices**

**# Matriz de todos ceros**

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
## Matriz de todos 1
np.ones((4,2,2), dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [24]:
#cualquier otro numero
np.full_like((2,2),99)

array([99, 99])

In [25]:
#cualquier otro numero(full_like)
np.full_like(a,4)

array([4, 4, 4])

In [27]:
# Números decimales aleatorios
np.random.rand(4,2)

array([[0.48589373, 0.4502196 ],
       [0.41148128, 0.8582206 ],
       [0.30700064, 0.89785816],
       [0.48190069, 0.98959274]])

In [28]:
# Valores enteros aleatorios
np.random.randint(-4,8, size=(3,3))

array([[ 4,  1, -4],
       [-2, -1,  1],
       [ 1, -2, -3]])

In [29]:
# La matriz de identidad
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Repetir una matriz
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output = np.ones((5,5))
print(output)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [33]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**¡Ten cuidado al copiar matrices!**

In [34]:
a1 = np.array([1,2,3])
b1 = a1.copy()
b1[0] = 100
print(a1)

[1 2 3]


**Matemáticas**

In [35]:
a2 = np.array([1,2,3,4])
print(a2)

[1 2 3 4]


In [36]:
a2 + 2

array([3, 4, 5, 6])

In [37]:
a2 - 2

array([-1,  0,  1,  2])

In [38]:
a2 * 2

array([2, 4, 6, 8])

In [39]:
a2 / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b2 = np.array([1,0,1,0])
a2 + b2


array([2, 2, 4, 4])

In [41]:
a2 ** 2

array([ 1,  4,  9, 16])

In [42]:
np.cos(a2)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Por mucho mas (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

**Algebra lineal**

In [43]:
a3 = np.ones((2,3))
print(a3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [44]:
b3 =np.full((3,2),2 )
print(b3)

[[2 2]
 [2 2]
 [2 2]]


In [45]:
# Encuentra el determinante
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

**Estadística**

In [46]:
stats = np.array([[1,2,3],[ 4,5,6]])

In [47]:
np.min(stats)

np.int64(1)

In [48]:
np.max(stats, axis=1)

array([3, 6])

In [49]:
np.sum(stats, axis=0)

array([5, 7, 9])

**Reorganización de matrices**

In [50]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [52]:
# Vectores apilados verticalmente
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
# Pila horizontal
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Misceláneos**
Cargar datos desde el archivo

In [55]:
filedata = np.genfromtxt("data.txt", delimiter=",")
filedata = filedata.astype("int32")
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


**Enmascaramiento booleano e indexación avanzada**

In [56]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])